// app/(home)/login/page.tsx
"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { useUser } from "@/context/user-context";

export default function Login() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const router = useRouter();
  const { toast } = useToast();
  const { fetchUser, user } = useUser();

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);

    try {
      const response = await fetch("/api/auth/login", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email, password }),
      });

      const data = await response.json();

      if (response.ok) {
        await fetchUser();
        router.refresh();
        setTimeout(() => {
          router.push("/dashboard");
        }, 150);
      } else {
        toast({
          variant: "destructive",
          title: "Login Failed",
          description: data.message || "Something went wrong",
        });
      }
    } catch (error) {
      toast({
        variant: "destructive",
        title: "Error",
        description: "Failed to connect to server",
      });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex-1 flex items-center justify-between w-full">
      <Card className="max-w-md mx-auto mt-10">
        <CardHeader>
          <CardTitle className="text-2xl text-center font-bold text-purple-600 dark:text-purple-400">
            Login
          </CardTitle>
          <CardDescription className="text-center">
            Welcome back! Please log in to your account
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleLogin}>
            <div className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="email">Email</Label>
                <Input
                  id="email"
                  type="email"
                  placeholder="Email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  required
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="password">Password</Label>
                <Input
                  id="password"
                  type="password"
                  placeholder="Password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  required
                />
              </div>
            </div>
            <Button className="w-full mt-6" type="submit" disabled={isLoading}>
              {isLoading ? "Logging in..." : "Login"}
            </Button>
          </form>
        </CardContent>
        <CardFooter className="justify-center">
          <p className="text-sm text-gray-600 dark:text-gray-400">
            Don't have an account?{" "}
            <a
              href="/signup"
              className="text-purple-600 dark:text-purple-400 hover:underline"
            >
              Sign up
            </a>
          </p>
        </CardFooter>
      </Card>
    </div>
  );
}

// pages/login/index.vue
<template>
  <div>
    <!-- Header -->
    <div class="sm:mx-auto sm:w-full sm:max-w-md">
      <h1 class="text-2xl font-bold text-foreground text-center">
        Log in to your account
      </h1>
      <p class="mt-2 text-center text-sm text-muted-foreground">
        Welcome back to Infinite Humans
      </p>
    </div>

    <div class="mt-8">
      <form @submit.prevent="handleSubmit" class="space-y-4">
        <div class="space-y-1">
          <label for="email" class="block text-sm font-medium text-foreground">
            Email address
          </label>
          <input
            id="email"
            v-model="form.email"
            type="email"
            class="w-full px-3 py-2 border border-input rounded-md bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-1"
            required
          />
        </div>

        <div class="space-y-1">
          <label
            for="password"
            class="block text-sm font-medium text-foreground"
          >
            Password
          </label>
          <input
            id="password"
            v-model="form.password"
            type="password"
            class="w-full px-3 py-2 border border-input rounded-md bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-1"
            required
          />
        </div>

        <UiButton type="submit" class="w-full" :disabled="auth.loading">
          {{ auth.loading ? "Logging in..." : "Log in" }}
        </UiButton>

        <p v-if="error" class="text-destructive text-sm text-center">
          {{ error }}
        </p>
      </form>

      <div class="mt-6 text-center text-sm">
        <span class="text-muted-foreground">Don't have an account?</span>
        <NuxtLink to="/signup" class="text-primary hover:underline ml-1">
          Sign up
        </NuxtLink>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from "vue";
import { useAuthStore } from "~/stores/auth";
import { useRouter } from "nuxt/app";

definePageMeta({
  layout: "login",
});

const router = useRouter();
const auth = useAuthStore();
const error = ref("");

const form = ref({
  email: "",
  password: "",
});

const handleSubmit = async () => {
  error.value = "";
  try {
    await auth.login(form.value.email, form.value.password);
    router.push("/profile");
  } catch (err) {
    error.value = "Invalid email or password";
  }
};
</script>
